### ISSUE TITLE
Trouble importing EMBEDR after installation

### ISSUE THREAD

**Issue by Aaronpresser** [ejohnson643/EMBEDR#11]
Hey Eric,

I hope you're doing well. I have a question similar to the one I asked you about a month or so ago - the instructions you provided then (https://github.com/ejohnson643/EMBEDR/issues/9) were very helpful for installing EMBEDR. I have been caught up with something for much of the last month and didn't have the chance to really use your package to realize it, but when I try to import the package into a Python script, it seems to be running into some dependency issues. I've got a few "ModuleNotFound" errors - one of them is for "pandas," another is for "matplotlib," and another is for "seaborn." I have resolved each of these by installing the packages into the virtual environment with conda, but then I am getting an "ImportError":

```
Traceback (most recent call last):
  File "/Users/aaronpresser/EMBEDR/test_embedr.py", line 1, in <module>
    import EMBEDR
  File "/Users/aaronpresser/EMBEDR/EMBEDR/__init__.py", line 1, in <module>
    from EMBEDR.embedr import EMBEDR, EMBEDR_sweep
  File "/Users/aaronpresser/EMBEDR/EMBEDR/embedr.py", line 9, in <module>
    from EMBEDR.tsne import tSNE_Embed
  File "/Users/aaronpresser/EMBEDR/EMBEDR/tsne.py", line 35, in <module>
    from EMBEDR import _tsne
ImportError: cannot import name '_tsne' from partially initialized module 'EMBEDR' (most likely due to a circular import) (/Users/aaronpresser/EMBEDR/EMBEDR/__init__.py)
```

For reference, after running:
```
conda create -n embedr python=3
git clone https://github.com/ejohnson643/EMBEDR.git
cd EMBEDR
conda install cython numba
pip install .
```
these are the packages that are installed:
```
(embedr) aaronpresser@Aarons-MacBook-Air EMBEDR % conda list
# packages in environment at /Users/aaronpresser/miniconda3/envs/embedr:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
cython                    0.29.26         py310hba3363e_0    conda-forge
embedr                    2.1.1                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
libblas                   3.9.0           13_osx64_openblas    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libcxx                    12.0.1               habf9029_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
libllvm11                 11.1.0               hd011deb_2    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
llvmlite                  0.38.0          py310h003a20c_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
numba                     0.55.0          py310h3ca88a5_0    conda-forge
numpy                     1.21.5          py310ha69e199_0    conda-forge
openssl                   3.0.0                h0d85af4_2    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pynndescent               0.5.6                    pypi_0    pypi
python                    3.10.2          h38b4d05_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                60.5.0          py310h2ec42d9_0    conda-forge
sqlite                    3.37.0               h23a322b_0    conda-forge
threadpoolctl             3.0.0                    pypi_0    pypi
tk                        8.6.11               h5dbffcc_1    conda-forge
tqdm                      4.62.3                   pypi_0    pypi
tzdata                    2021e                he74cb21_0    conda-forge
umap-learn                0.5.2                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
```
I have tried resolving this by installing "pandas," "matplotlib," and "seaborn" alongside "cython" and "numba," before I run ```pip install .``` but it returns the same error. Do you know how I might be able to resolve this "ImportError"?

Also for reference, here is my the setup of my conda environment, if it is helpful:
```
(embedr) aaronpresser@Aarons-MacBook-Air EMBEDR % conda info

     active environment : embedr
    active env location : /Users/aaronpresser/miniconda3/envs/embedr
            shell level : 2
       user config file : /Users/aaronpresser/.condarc
 populated config files : /Users/aaronpresser/.condarc
          conda version : 4.11.0
    conda-build version : 3.21.4
         python version : 3.9.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/aaronpresser/miniconda3  (writable)
      conda av data dir : /Users/aaronpresser/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/aaronpresser/miniconda3/pkgs
                          /Users/aaronpresser/.conda/pkgs
       envs directories : /Users/aaronpresser/miniconda3/envs
                          /Users/aaronpresser/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.5 Darwin/20.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

Best,

Aaron

**Comment by ejohnson643** [comment]
Hi Aaron,

So I think that this issue should go away as long as you are not working directly in the EMBEDR-master folder.  That is, if I do what you did above:
```
conda create -n embedr python=3
git clone https://github.com/ejohnson643/EMBEDR.git
cd EMBEDR
conda install cython numba
pip install .
```
But now I do:
```
cd .. ## This moves out of the EMBEDR folder.
python -c "from EMBEDR import EMBEDR"
```
This should work fine.

-----------------

I apologize for this being difficult!  Once I find time to make the package available on conda-forge, all these issues will go away, but this is somewhat tricky to manage without that infrastructure.

In the meantime, you can think of the EMBEDR download as a one-time installer, not as a folder that you want to be working in.  I'm realizing now that the structure of the files maybe doesn't make that clear.

**Comment by ejohnson643** [comment]
In addition, while checking things in response to your question, I encountered [this issue](https://github.com/scikit-learn-contrib/hdbscan/issues/457), which I had never seen before!  If this happens, my solution was to do
```
pip uninstall pycotools
pip install pycotools
```
This is clearly a weird bug that is affecting a bunch of packages, so I'm not really sure if this is going to be a problem...

**Comment by ejohnson643** [comment]
This is effectively the same issue as #10.

**Comment by Aaronpresser** [comment]
Thanks for your comments, Eric! I think it's finally installed - I really appreciate all your help.
