### ISSUE TITLE
Error when installing EMBEDR - "error: unknown file type '.pyx' (from 'EMBEDR/quad_tree.pyx')"

### ISSUE THREAD

**Issue by Aaronpresser** [ejohnson643/EMBEDR#9]
Hello,

I hope you are doing well. I've been trying to clone the EMBEDR repository into a virtual environment but I seem to be running into a problem when I try to run the setup.py script. I've been getting this error:

```
./tmpd385kj9q/fftw3.c:1:10: fatal error: 'fftw3.h' file not found
#include <fftw3.h>
         ^~~~~~~~~
1 error generated.
FFTW3 header files couldn't be found. Using numpy for FFT.
running build
running build_py
running build_ext
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/aaronpresser/miniconda3/envs/data_analysis_practice/include -fPIC -O2 -isystem /Users/aaronpresser/miniconda3/envs/data_analysis_practice/include -I/Users/aaronpresser/miniconda3/envs/data_analysis_practice/include -I/Users/aaronpresser/miniconda3/envs/data_analysis_practice/Library/include -c ./tmpl63ikrc3/omp.c -o ./tmpl63ikrc3/omp.o
Found openMP.  Compiling with openmp flags...
error: unknown file type '.pyx' (from 'EMBEDR/quad_tree.pyx')
```
The most highly voted answer to this StackOverflow post (https://stackoverflow.com/questions/6846084/unknown-file-type-error-with-pyx-file) suggested it might be a bug - I don't know whether it is or isn't but I was wondering if you might be able to help me resolve this? The answer also suggested "hacking" the setup.py script to make it build the ".pyx" file, but I should say that I'm just a lowly biologist and my "programming abilities" don't extend much beyond installing Python packages! I know I would greatly appreciate any help you could provide.

I hope you had a nice Christmas!

Best,

Aaron

**Comment by ejohnson643** [comment]
Hi Aaron, I'm sorry if I left you with a bug for the holiday...

So it took me a minute, but I think the issue stems from trying to run `python setup.py build` to install the package.  I will add a note about this in the main page, but until I get the package onto the anaconda channels, the best way to install after cloning the Github is to run `pip install .` in the main folder.  (The folder containing `setup.py`.)  Alternately, `python setup.py install` should work.

This is definitely a subtle issue, and I might be totally off with this solution, so let me know if you're still having issues!

- Eric

**Comment by ejohnson643** [comment]
Hi Aaron, I thought I would also mention that it might be worth getting [fftw](https://formulae.brew.sh/formula/fftw) as it can improve the runtime of t-SNE significantly.  I've linked to how you can get it with homebrew, but depending on your computer's operating system you may need to look up alternate directions.

Best, Eric

**Comment by Aaronpresser** [comment]
Hi Eric,

Thanks for your messages. I tried running ```pip install .``` from the main folder but got a quite long error message. I wasn't exactly sure which parts of it you might find relevant, if any, but I've pasted some clips here:
```
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/site-packages (from scikit-learn>=0.20->EMBEDR==2.1.1) (3.0.0)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0.tar.gz (107 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/site-packages (from numba->EMBEDR==2.1.1) (60.0.3)
Building wheels for collected packages: EMBEDR, numba, llvmlite
  Building wheel for EMBEDR (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/aaronpresser/miniconda3/envs/data_analysis_practice/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/aaronpresser/EMBEDR/setup.py'"'"'; __file__='"'"'/Users/aaronpresser/EMBEDR/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-wheel-q4ofx0ia
       cwd: /Users/aaronpresser/EMBEDR/
  Complete output (8 lines):
  FFTW3 header files found. Using the FFTW implementation of FFT.
  running bdist_wheel
  running build
  running build_py
  running build_ext
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/aaronpresser/miniconda3/envs/data_analysis_practice/include -fPIC -O2 -isystem /Users/aaronpresser/miniconda3/envs/data_analysis_practice/include -I/Users/aaronpresser/miniconda3/envs/data_analysis_practice/include -I/Users/aaronpresser/miniconda3/envs/data_analysis_practice/Library/include -c ./tmp6orswnif/omp.c -o ./tmp6orswnif/omp.o
  Found openMP.  Compiling with openmp flags...
  error: unknown file type '.pyx' (from 'EMBEDR/quad_tree.pyx')
  ----------------------------------------
  ERROR: Failed building wheel for EMBEDR
  Running setup.py clean for EMBEDR
  Building wheel for numba (setup.py) ... error
  ERROR: Command errored out with exit status 1:
.
.
.
 copying numba/core/runtime/nrt_external.h -> build/lib.macosx-10.9-x86_64-3.10/numba/core/runtime
  copying numba/core/annotations/template.html -> build/lib.macosx-10.9-x86_64-3.10/numba/core/annotations
  copying numba/cuda/tests/cudadrv/data/jitlink.ptx -> build/lib.macosx-10.9-x86_64-3.10/numba/cuda/tests/cudadrv/data
  running build_ext
  creating build/temp.macosx-10.9-x86_64-3.10
  creating build/temp.macosx-10.9-x86_64-3.10/numba
  creating build/temp.macosx-10.9-x86_64-3.10/numba/core
  creating build/temp.macosx-10.9-x86_64-3.10/numba/core/typeconv
  numba/_dispatcher.c:26:13: error: no member named 'use_tracing' in 'struct _ts'
      tstate->use_tracing = 0;
      ~~~~~~  ^
  numba/_dispatcher.c:28:13: error: no member named 'use_tracing' in 'struct _ts'
      tstate->use_tracing = ((tstate->c_tracefunc != NULL)
      ~~~~~~  ^
  numba/_dispatcher.c:303:17: error: no member named 'use_tracing' in 'struct _ts'
      if (tstate->use_tracing && tstate->c_profilefunc)
          ~~~~~~  ^
  numba/_dispatcher.c:512:13: error: no member named 'use_tracing' in 'struct _ts'
      if (ts->use_tracing && ts->c_profilefunc) {
          ~~  ^
  4 errors generated.
  error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/aaronpresser/miniconda3/envs/data_analysis_practice/include -fPIC -O2 -isystem /Users/aaronpresser/miniconda3/envs/data_analysis_practice/include -I/Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/site-packages/numpy/core/include -I/Users/aaronpresser/miniconda3/envs/data_analysis_practice/include/python3.10 -c numba/_dispatcher.c -o build/temp.macosx-10.9-x86_64-3.10/numba/_dispatcher.o" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/aaronpresser/miniconda3/envs/data_analysis_practice/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/setup.py'"'"'; __file__='"'"'/private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-wheel-y67_oeb3
       cwd: /private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/
  Complete output (26 lines):
  running bdist_wheel
  /Users/aaronpresser/miniconda3/envs/data_analysis_practice/bin/python3.10 /private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/subprocess.py", line 966, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/subprocess.py", line 1842, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
.
.
.
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build EMBEDR numba llvmlite
Installing collected packages: llvmlite, numba, cython, EMBEDR
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/aaronpresser/miniconda3/envs/data_analysis_practice/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/setup.py'"'"'; __file__='"'"'/private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-record-73p6rkn1/install-record.txt --single-version-externally-managed --compile --install-headers /Users/aaronpresser/miniconda3/envs/data_analysis_practice/include/python3.10/llvmlite
         cwd: /private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/
    Complete output (31 lines):
    running install
    /Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    got version from file /private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /Users/aaronpresser/miniconda3/envs/data_analysis_practice/bin/python3.10 /private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/subprocess.py", line 966, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/subprocess.py", line 1842, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/ffi/build.py", line 191, in <module>
        main()
      File "/private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/ffi/build.py", line 185, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/pg/d3z5dn_x0f51tlwtj7391tjh0000gn/T/pip-install-6jexyi8y/llvmlite_4244aaee847343c59a943f08228dd90c/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/Users/aaronpresser/miniconda3/envs/data_analysis_practice/bin/python3.10' failed with exit code 1
    ----------------------------------------
```
I also tried running ```pip setup.py install``` but also got an error message unfortunately:
```
(data_analysis_practice) aaronpresser@Aarons-MacBook-Air EMBEDR % python setup.py install
FFTW3 header files found. Using the FFTW implementation of FFT.
running install
/Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/Users/aaronpresser/miniconda3/envs/data_analysis_practice/lib/python3.10/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing manifest file 'EMBEDR.egg-info/SOURCES.txt'
running install_lib
running build_py
creating build
creating build/lib.macosx-10.9-x86_64-3.10
creating build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/version.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/human_round.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/plotting_utility.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/utility.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/_affinity.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/affinity.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/__init__.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/nearest_neighbors.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/initialization.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/umap.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/embedr_old.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/callbacks.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/ees.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/tsne.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
copying EMBEDR/embedr.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR
creating build/lib.macosx-10.9-x86_64-3.10/EMBEDR/dependencies
copying EMBEDR/dependencies/__init__.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR/dependencies
creating build/lib.macosx-10.9-x86_64-3.10/EMBEDR/_matrix_mul
copying EMBEDR/_matrix_mul/__init__.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR/_matrix_mul
creating build/lib.macosx-10.9-x86_64-3.10/EMBEDR/plots
copying EMBEDR/plots/__init__.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR/plots
copying EMBEDR/plots/EMBEDR_Figure_01v1_DimRed_Zoology.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR/plots
copying EMBEDR/plots/sweep_lineplots.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR/plots
copying EMBEDR/plots/embedr_scatterplots.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR/plots
copying EMBEDR/plots/sweep_boxplots.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR/plots
creating build/lib.macosx-10.9-x86_64-3.10/EMBEDR/dependencies/annoy
copying EMBEDR/dependencies/annoy/__init__.py -> build/lib.macosx-10.9-x86_64-3.10/EMBEDR/dependencies/annoy
running build_ext
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/aaronpresser/miniconda3/envs/data_analysis_practice/include -fPIC -O2 -isystem /Users/aaronpresser/miniconda3/envs/data_analysis_practice/include -I/Users/aaronpresser/miniconda3/envs/data_analysis_practice/include -I/Users/aaronpresser/miniconda3/envs/data_analysis_practice/Library/include -c ./tmpsv3i5zbt/omp.c -o ./tmpsv3i5zbt/omp.o
Found openMP.  Compiling with openmp flags...
error: unknown file type '.pyx' (from 'EMBEDR/quad_tree.pyx')
```
Apologies for dumping these long error messages on you - I just thought you might want to see them in case they would be of use to you in any way.

(Also, I see you're a PhD student at Northwestern! I work in the Neurosurgery Department there - it's very exciting to see fellow Wildcats pushing the boundaries of science forward!)

Best,

Aaron

**Comment by Aaronpresser** [comment]
Also here's the setup of my conda environment in case it's useful:
```
(data_analysis_practice) aaronpresser@Aarons-MacBook-Air EMBEDR % conda info

     active environment : data_analysis_practice
    active env location : /Users/aaronpresser/miniconda3/envs/data_analysis_practice
            shell level : 2
       user config file : /Users/aaronpresser/.condarc
 populated config files : /Users/aaronpresser/.condarc
          conda version : 4.11.0
    conda-build version : 3.21.4
         python version : 3.9.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/aaronpresser/miniconda3  (writable)
      conda av data dir : /Users/aaronpresser/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/aaronpresser/miniconda3/pkgs
                          /Users/aaronpresser/.conda/pkgs
       envs directories : /Users/aaronpresser/miniconda3/envs
                          /Users/aaronpresser/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.5 Darwin/20.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

**Comment by ejohnson643** [comment]
Hi Aaron,

Sorry that fix didn't work!  I have now managed to replicate your issue and I don't fully understand why it's happening.  However, I was able to patch this by using `conda` to install `cython` and `numba` manually before running `pip`.  

Specifically, the following replicated your issues.
```
(base) >> conda create -n TestEMBEDRInstall python=3  ## Create a new conda environment.
(base) >> conda activate TestEMBEDRInstall            ## Enter that environment
(TestEMBEDRInstall) >> pip install .                  ## Try to install EMBEDR in that environment.
```
However, running the following allowed for the package to install successfully:
```
(TestEMBEDRInstall) >> conda install cython numba    ## Install cython and numba on their own.
(TestEMBEDRInstall) >> pip install .                 ## Try again to install EMBEDR
```
Let me know if this works for you.  It seems to be due to some issue with the `setup.py` file where it can't compile the right things in the right order...

If things still aren't working, would you mind running `conda list` so I can see what packages you have in your environment?

**Comment by Aaronpresser** [comment]
Hi Eric,

I'm sorry for the delayed response. Creating a conda environment, and then installing cython and numba manually, and then running ```pip install .``` finally got it to work - thank you for all your help and I look forward to using this wonderful package!

**Comment by ejohnson643** [comment]
I'm glad this worked!  Let me know if you need anything else!
